$(document).ready(function(){
    $("#gnb>li").on("mousemove",function(){
        $(".submenu").stop().slideDown(300);
        $(".menubg").stop().slideDown(300);
    });
    $("#gnb>li").on("mouseleave",function(){
        $(".submenu").stop().slideUp(300);
        $(".menubg").stop().slideUp(300);
    });
})
